--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;
--
-- Name: cache; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.cache (
    key character varying(255) NOT NULL,
    value text NOT NULL,
    expiration integer NOT NULL
);


ALTER TABLE public.cache OWNER TO eventos;

--
-- Name: cache_locks; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.cache_locks (
    key character varying(255) NOT NULL,
    owner character varying(255) NOT NULL,
    expiration integer NOT NULL
);


ALTER TABLE public.cache_locks OWNER TO eventos;

--
-- Name: certificados; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.certificados (
    id bigint NOT NULL,
    codigo_autenticador character varying(255) NOT NULL,
    dt_criacao timestamp(0) without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.certificados OWNER TO eventos;

--
-- Name: certificados_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

CREATE SEQUENCE public.certificados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.certificados_id_seq OWNER TO eventos;

--
-- Name: certificados_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: eventos
--

ALTER SEQUENCE public.certificados_id_seq OWNED BY public.certificados.id;


--
-- Name: evento; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.evento (
    id integer NOT NULL,
    dt_criacao timestamp without time zone DEFAULT '2024-11-10 21:50:27.335501'::timestamp without time zone,
    dt_inicio timestamp without time zone,
    dt_fim timestamp without time zone,
    descricao text NOT NULL,
    layout_certificado text
);


ALTER TABLE public.evento OWNER TO eventos;

--
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

ALTER TABLE public.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: failed_jobs; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.failed_jobs (
    id bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.failed_jobs OWNER TO eventos;

--
-- Name: failed_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

CREATE SEQUENCE public.failed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.failed_jobs_id_seq OWNER TO eventos;

--
-- Name: failed_jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: eventos
--

ALTER SEQUENCE public.failed_jobs_id_seq OWNED BY public.failed_jobs.id;


--
-- Name: inscricao_evento; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.inscricao_evento (
    id integer NOT NULL,
    ref_pessoa integer NOT NULL,
    ref_evento integer NOT NULL,
    dt_inscricao timestamp without time zone DEFAULT now() NOT NULL,
    dt_cancelamento timestamp without time zone
);


ALTER TABLE public.inscricao_evento OWNER TO eventos;

--
-- Name: inscricao_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

ALTER TABLE public.inscricao_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inscricao_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_batches; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.job_batches (
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text NOT NULL,
    options text,
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer
);


ALTER TABLE public.job_batches OWNER TO eventos;

--
-- Name: jobs; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    queue character varying(255) NOT NULL,
    payload text NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL
);


ALTER TABLE public.jobs OWNER TO eventos;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

CREATE SEQUENCE public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO eventos;

--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: eventos
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- Name: migrations; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


ALTER TABLE public.migrations OWNER TO eventos;

--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.migrations_id_seq OWNER TO eventos;

--
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: eventos
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.password_reset_tokens (
    email character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    created_at timestamp(0) without time zone
);


ALTER TABLE public.password_reset_tokens OWNER TO eventos;

--
-- Name: presencas; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.presencas (
    id bigint NOT NULL,
    ref_pessoa bigint,
    ref_inscricao_evento bigint,
    dt_criacao timestamp(0) without time zone DEFAULT now()
);


ALTER TABLE public.presencas OWNER TO eventos;

--
-- Name: presencas_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

ALTER TABLE public.presencas ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.presencas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.sessions (
    id character varying(255) NOT NULL,
    user_id bigint,
    ip_address character varying(45),
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL
);


ALTER TABLE public.sessions OWNER TO eventos;

--
-- Name: users; Type: TABLE; Schema: public; Owner: eventos
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


ALTER TABLE public.users OWNER TO eventos;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: eventos
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO eventos;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: eventos
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: certificados id; Type: DEFAULT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.certificados ALTER COLUMN id SET DEFAULT nextval('public.certificados_id_seq'::regclass);


--
-- Name: failed_jobs id; Type: DEFAULT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.failed_jobs ALTER COLUMN id SET DEFAULT nextval('public.failed_jobs_id_seq'::regclass);


--
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: cache; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.cache (key, value, expiration) FROM stdin;
\.


--
-- Data for Name: cache_locks; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.cache_locks (key, owner, expiration) FROM stdin;
\.


--
-- Data for Name: certificados; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.certificados (id, codigo_autenticador, dt_criacao) FROM stdin;
1	cdc6fd8e09cdae9c5b9b7e40ec09bd2a	2024-11-30 19:58:47
2	cdc6fd8e09cdae9c5b9b7e40ec09bd2a	2024-11-30 19:59:19
\.


--
-- Data for Name: evento; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.evento (id, dt_criacao, dt_inicio, dt_fim, descricao, layout_certificado) FROM stdin;
2	2024-11-10 21:50:27.335501	\N	\N	Teste 2	\N
1	2024-11-10 21:50:27.335501	2024-11-30 16:06:00	\N	Teste	\N
\.


--
-- Data for Name: failed_jobs; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.failed_jobs (id, uuid, connection, queue, payload, exception, failed_at) FROM stdin;
\.


--
-- Data for Name: inscricao_evento; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.inscricao_evento (id, ref_pessoa, ref_evento, dt_inscricao, dt_cancelamento) FROM stdin;
4	3	1	2024-11-30 12:45:21.971194	\N
5	3	1	2024-11-30 13:52:13.908659	\N
6	3	1	2024-11-30 13:54:09.294811	\N
7	3	1	2024-11-30 13:56:41.466221	\N
1	3	1	2024-11-10 21:50:27.335501	2024-11-30 19:39:53
2	3	1	2024-11-10 21:50:27.335501	2024-11-30 19:43:41
3	3	1	2024-11-10 21:50:27.335501	2024-11-30 20:08:27
8	3	2	2024-11-30 20:01:43.409099	\N
\.


--
-- Data for Name: job_batches; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.job_batches (id, name, total_jobs, pending_jobs, failed_jobs, failed_job_ids, options, cancelled_at, created_at, finished_at) FROM stdin;
\.


--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.jobs (id, queue, payload, attempts, reserved_at, available_at, created_at) FROM stdin;
\.


--
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.migrations (id, migration, batch) FROM stdin;
7	0001_01_01_000000_create_users_table	1
8	0001_01_01_000001_create_cache_table	1
9	0001_01_01_000002_create_jobs_table	1
12	2024_11_30_195209_certificado_table	2
\.


--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.password_reset_tokens (email, token, created_at) FROM stdin;
\.


--
-- Data for Name: presencas; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.presencas (id, ref_pessoa, ref_inscricao_evento, dt_criacao) FROM stdin;
2	3	1	2024-11-30 15:28:38
3	3	1	2024-11-30 15:43:02
4	3	1	2024-11-30 15:52:14
5	3	1	2024-11-30 15:54:00
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.sessions (id, user_id, ip_address, user_agent, payload, last_activity) FROM stdin;
3kzWpTShWgpJgyvjEysyD7HflDaDqGYqHZt33X3y	3	127.0.0.1	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36	YTo1OntzOjY6Il90b2tlbiI7czo0MDoiWEpkZkNKTE9qMXZKNG5iYkpwdjREQ2RLdXEweTlwVG9wcFpSUzdlZyI7czozOiJ1cmwiO2E6MDp7fXM6OToiX3ByZXZpb3VzIjthOjE6e3M6MzoidXJsIjtzOjI5OiJodHRwOi8vMTI3LjAuMC4xOjgwMDMvZXZlbnRvcyI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6NTA6ImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtpOjM7fQ==	1733018999
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: eventos
--

COPY public.users (id, name, email, password, is_admin, created_at, updated_at) FROM stdin;
3	Teste	admin@teste.com	21232f297a57a5a743894a0e4a801fc3	t	2024-11-30 15:24:07	2024-11-30 15:24:07
\.


--
-- Name: certificados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.certificados_id_seq', 2, true);


--
-- Name: evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.evento_id_seq', 2, true);


--
-- Name: failed_jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.failed_jobs_id_seq', 1, false);


--
-- Name: inscricao_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.inscricao_evento_id_seq', 8, true);


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.jobs_id_seq', 1, false);


--
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.migrations_id_seq', 12, true);


--
-- Name: presencas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.presencas_id_seq', 5, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eventos
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: cache_locks cache_locks_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.cache_locks
    ADD CONSTRAINT cache_locks_pkey PRIMARY KEY (key);


--
-- Name: cache cache_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.cache
    ADD CONSTRAINT cache_pkey PRIMARY KEY (key);


--
-- Name: certificados certificados_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.certificados
    ADD CONSTRAINT certificados_pkey PRIMARY KEY (id);


--
-- Name: evento evento_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.evento
    ADD CONSTRAINT evento_pkey PRIMARY KEY (id);


--
-- Name: failed_jobs failed_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_pkey PRIMARY KEY (id);


--
-- Name: failed_jobs failed_jobs_uuid_unique; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.failed_jobs
    ADD CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid);


--
-- Name: inscricao_evento inscricao_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.inscricao_evento
    ADD CONSTRAINT inscricao_evento_pkey PRIMARY KEY (id);


--
-- Name: job_batches job_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.job_batches
    ADD CONSTRAINT job_batches_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email);


--
-- Name: presencas presencas_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.presencas
    ADD CONSTRAINT presencas_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: jobs_queue_index; Type: INDEX; Schema: public; Owner: eventos
--

CREATE INDEX jobs_queue_index ON public.jobs USING btree (queue);


--
-- Name: sessions_last_activity_index; Type: INDEX; Schema: public; Owner: eventos
--

CREATE INDEX sessions_last_activity_index ON public.sessions USING btree (last_activity);


--
-- Name: sessions_user_id_index; Type: INDEX; Schema: public; Owner: eventos
--

CREATE INDEX sessions_user_id_index ON public.sessions USING btree (user_id);


--
-- Name: presencas fk_inscricao_evento; Type: FK CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.presencas
    ADD CONSTRAINT fk_inscricao_evento FOREIGN KEY (ref_inscricao_evento) REFERENCES public.inscricao_evento(id);


--
-- Name: presencas fk_pessoa; Type: FK CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.presencas
    ADD CONSTRAINT fk_pessoa FOREIGN KEY (ref_pessoa) REFERENCES public.users(id);


--
-- Name: inscricao_evento inscricao_evento_ref_inscricao_fkey; Type: FK CONSTRAINT; Schema: public; Owner: eventos
--

ALTER TABLE ONLY public.inscricao_evento
    ADD CONSTRAINT inscricao_evento_ref_inscricao_fkey FOREIGN KEY (ref_evento) REFERENCES public.evento(id);


--
-- PostgreSQL database dump complete
--

