services:
  users:
    build:
      context: ./users
    ports:
      - "8000:8000"
    volumes:
      - ./users:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8001:8000"
    volumes:
      - ./api-gateway:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  eventos:
    build:
      context: ./eventos
    ports:
      - "8002:8000"
    volumes:
      - ./eventos:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  front:
    build:
      context: ./front
    ports:
      - "8003:8000"
    volumes:
      - ./front:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  inscricao_evento:
    build:
      context: ./inscricao_evento
    ports:
      - "8004:8000"
    volumes:
      - ./inscricao_evento:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  presencas:
    build:
      context: ./presencas
    ports:
      - "8005:8000"
    volumes:
      - ./presencas:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

  certificado:
    build:
      context: ./certificado
    ports:
      - "8006:8000"
    volumes:
      - ./certificado:/var/www
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - postgres

     # Serviço do PostgreSQL
  postgres:
    image: postgres:16
    container_name: psql-db
    environment:
      POSTGRES_USER: eventos
      POSTGRES_PASSWORD: eventos
      POSTGRES_DB: eventos
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

volumes:
  psql_data:
    driver: local